import { describe, it, expect } from "vitest";
import { renderQuotePdfBytes, type QuotePdfData } from "./quote-pdf.server";

const base: QuotePdfData = {
  quoteRef: "abcd1234",
  createdAt: new Date("2026-08-01T00:00:00Z"),
  validUntil: new Date("2026-08-15T00:00:00Z"),
  companyName: "Acme Wholesale",
  buyerEmail: "buyer@acme.example",
  poReference: "PO-77",
  currencyCode: "USD",
  lines: [
    { title: "Stoneware Mug", sku: "MUG-12", quantity: 10, price: 9.5 },
    { title: "Matching Lid", sku: "LID-12", quantity: 10, price: 5 },
  ],
  brand: { name: "Acme Wholesale", primaryColor: "#4F46E5" },
  whiteLabel: false,
  locale: null,
};

function toStr(b: Uint8Array) { return Buffer.from(b).toString("latin1"); }

describe("renderQuotePdfBytes (pure)", () => {
  it("produces a valid branded PDF with the quote content", () => {
    const s = toStr(renderQuotePdfBytes(base));
    expect(s.startsWith("%PDF-1.4")).toBe(true);
    expect(s.trimEnd().endsWith("%%EOF")).toBe(true);
    expect(s).toContain("(QUOTE) Tj");
    expect(s).toContain("(#abcd1234) Tj");
    expect(s).toContain("(Stoneware Mug) Tj");
    expect(s).toContain("(USD 95.00) Tj"); // 10 × 9.50 line amount
    expect(s).toContain("(USD 145.00) Tj"); // estimated subtotal
    expect(s).toContain("Generated by Mannon");
  });

  it("white-label removes the Mannon footer", () => {
    const s = toStr(renderQuotePdfBytes({ ...base, whiteLabel: true }));
    expect(s).not.toContain("Generated by Mannon");
  });

  it("renders a second locale (fr) labels", () => {
    const s = toStr(renderQuotePdfBytes({ ...base, locale: "fr-CA" }));
    expect(s).toContain("(DEVIS) Tj");
    expect(s).toContain("(Sous-total"); // "Sous-total estimé" (accented, latin1)
    expect(s).toContain("Généré par Mannon");
  });

  it("caps rows and notes the overflow", () => {
    const many = Array.from({ length: 40 }, (_, i) => ({ title: `Item ${i}`, sku: null, quantity: 1, price: 1 }));
    const s = toStr(renderQuotePdfBytes({ ...base, lines: many }));
    expect(s).toContain("more item"); // "…and 12 more item(s)"
    expect(s).toContain("(USD 40.00) Tj"); // subtotal still sums ALL 40 rows
  });
});
