import prisma from "../db.server";
import { PdfBuilder, A4 } from "../lib/pdf";
import { getBrandingTokens } from "./branding.server";
import { whiteLabelAllowed } from "../lib/billing";

/**
 * F25.1 — branded quote PDF (server-side, dependency-free). A quote is an
 * *estimate*: we present the buyer's negotiated line prices and an estimated
 * subtotal, clearly noting that tax + the final total are calculated by Shopify at
 * checkout (guardrail #1 — we never compute tax/totals). Branding comes from F20;
 * white-label removes the Mannon footer (Growth). Localized labels render a second
 * locale. The layout is a pure function so it's unit-testable without a DB.
 */

export interface QuotePdfLine {
  title: string;
  sku: string | null;
  quantity: number;
  price: number; // agreed unit price
}

export interface QuotePdfData {
  quoteRef: string; // short, non-sensitive
  createdAt: Date;
  validUntil: Date | null;
  companyName: string;
  buyerEmail: string;
  poReference: string | null;
  currencyCode: string;
  lines: QuotePdfLine[];
  brand: { name: string; primaryColor: string | null };
  whiteLabel: boolean;
  locale?: string | null;
}

type Labels = Record<"quote" | "date" | "validUntil" | "billTo" | "item" | "sku" | "qty" | "unit" | "amount" | "estSubtotal" | "taxNote" | "notes" | "generatedBy" | "more", string>;

const LABELS: Record<string, Labels> = {
  en: { quote: "QUOTE", date: "Date", validUntil: "Valid until", billTo: "Prepared for", item: "Item", sku: "SKU", qty: "Qty", unit: "Unit", amount: "Amount", estSubtotal: "Estimated subtotal", taxNote: "Tax and the final total are calculated at checkout.", notes: "Notes", generatedBy: "Generated by Mannon", more: "…and {n} more item(s)" },
  fr: { quote: "DEVIS", date: "Date", validUntil: "Valable jusqu’au", billTo: "Préparé pour", item: "Article", sku: "Réf.", qty: "Qté", unit: "Prix", amount: "Montant", estSubtotal: "Sous-total estimé", taxNote: "La taxe et le total final sont calculés au paiement.", notes: "Notes", generatedBy: "Généré par Mannon", more: "…et {n} article(s) de plus" },
  es: { quote: "PRESUPUESTO", date: "Fecha", validUntil: "Válido hasta", billTo: "Preparado para", item: "Artículo", sku: "SKU", qty: "Cant.", unit: "Precio", amount: "Importe", estSubtotal: "Subtotal estimado", taxNote: "El impuesto y el total final se calculan al pagar.", notes: "Notas", generatedBy: "Generado por Mannon", more: "…y {n} artículo(s) más" },
};

function labelsFor(locale: string | null | undefined): Labels {
  if (!locale) return LABELS.en;
  const base = locale.trim().toLowerCase().split("-")[0];
  return LABELS[base] ?? LABELS.en;
}

function hexToRgb(hex: string | null): [number, number, number] | null {
  if (!hex) return null;
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return null;
  const n = parseInt(m[1], 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

const MAX_ROWS = 28;

/** Pure: compose the PDF bytes for a quote. No DB, no Shopify — unit-testable. */
export function renderQuotePdfBytes(data: QuotePdfData): Uint8Array {
  const L = labelsFor(data.locale);
  const money = (n: number) => `${data.currencyCode} ${n.toFixed(2)}`;
  const date = (d: Date) => d.toISOString().slice(0, 10);
  const brandColor = hexToRgb(data.brand.primaryColor) ?? [0.31, 0.275, 0.898]; // indigo default
  const ink: [number, number, number] = [0.1, 0.1, 0.18];
  const subdued: [number, number, number] = [0.42, 0.4, 0.5];
  const M = 40; // margin
  const right = A4.width - M;
  const doc = new PdfBuilder();

  // Brand header band.
  doc.rect(0, 0, A4.width, 6, { fill: brandColor });
  doc.text(M, 46, data.brand.name, { size: 20, bold: true, color: brandColor });
  doc.text(right, 40, L.quote, { size: 22, bold: true, color: ink, align: "right", maxX: right });
  doc.text(right, 60, `#${data.quoteRef}`, { size: 11, color: subdued, align: "right", maxX: right });

  // Meta.
  let y = 92;
  doc.text(M, y, `${L.billTo}: ${data.companyName}`, { size: 11, color: ink });
  doc.text(M, y + 15, data.buyerEmail, { size: 10, color: subdued });
  doc.text(right, y, `${L.date}: ${date(data.createdAt)}`, { size: 10, color: subdued, align: "right", maxX: right });
  if (data.validUntil) doc.text(right, y + 15, `${L.validUntil}: ${date(data.validUntil)}`, { size: 10, color: subdued, align: "right", maxX: right });

  // Table header.
  y = 140;
  const cols = { item: M, sku: 300, qty: 380, unit: 440, amount: right };
  doc.rect(M, y - 12, A4.width - 2 * M, 22, { fill: [0.95, 0.95, 0.98] });
  doc.text(cols.item + 4, y + 3, L.item, { size: 9, bold: true, color: subdued });
  doc.text(cols.sku, y + 3, L.sku, { size: 9, bold: true, color: subdued });
  doc.text(cols.qty, y + 3, L.qty, { size: 9, bold: true, color: subdued, align: "right", maxX: cols.qty + 30 });
  doc.text(cols.unit, y + 3, L.unit, { size: 9, bold: true, color: subdued, align: "right", maxX: cols.unit + 55 });
  doc.text(right, y + 3, L.amount, { size: 9, bold: true, color: subdued, align: "right", maxX: right });

  // Rows.
  y += 26;
  let subtotal = 0;
  const shown = data.lines.slice(0, MAX_ROWS);
  for (const line of shown) {
    const amount = line.quantity * line.price;
    subtotal += amount;
    doc.text(cols.item + 4, y, line.title.slice(0, 48), { size: 10, color: ink });
    if (line.sku) doc.text(cols.sku, y, line.sku.slice(0, 16), { size: 9, color: subdued });
    doc.text(cols.qty, y, String(line.quantity), { size: 10, color: ink, align: "right", maxX: cols.qty + 30 });
    doc.text(cols.unit, y, money(line.price), { size: 10, color: ink, align: "right", maxX: cols.unit + 55 });
    doc.text(right, y, money(amount), { size: 10, color: ink, align: "right", maxX: right });
    doc.line(M, y + 8, right, y + 8, { color: [0.9, 0.89, 0.94] });
    y += 22;
  }
  for (const line of data.lines.slice(MAX_ROWS)) subtotal += line.quantity * line.price;
  if (data.lines.length > MAX_ROWS) {
    doc.text(M + 4, y, L.more.replace("{n}", String(data.lines.length - MAX_ROWS)), { size: 9, color: subdued });
    y += 20;
  }

  // Totals (estimate) + tax note.
  y += 8;
  doc.text(cols.unit, y, L.estSubtotal, { size: 11, bold: true, color: ink, align: "right", maxX: cols.unit + 55 });
  doc.text(right, y, money(subtotal), { size: 11, bold: true, color: ink, align: "right", maxX: right });
  doc.text(M, y, L.taxNote, { size: 8, color: subdued });

  // Notes.
  if (data.poReference) {
    y += 30;
    doc.text(M, y, `${L.notes}: PO ${data.poReference}`, { size: 10, color: subdued });
  }

  // Footer (removed under white-label).
  if (!data.whiteLabel) {
    doc.text(M, A4.height - 30, L.generatedBy, { size: 8, color: subdued });
  }

  return doc.build();
}

/**
 * Load a shop-owned quote and render its branded PDF. Returns null when the quote
 * isn't found for this shop. `plan` decides white-label; `locale` picks the label
 * language (defaults to English).
 */
export async function renderQuotePdf(
  shopDomain: string,
  quoteId: string,
  opts: { currencyCode: string; plan: string | null; locale?: string | null },
): Promise<{ filename: string; bytes: Uint8Array; buyerEmail: string; shopId: string } | null> {
  const shop = await prisma.shop.findUnique({ where: { shopifyDomain: shopDomain }, select: { id: true } });
  if (!shop) return null;
  const quote = await prisma.quote.findFirst({
    where: { id: quoteId, company: { shopId: shop.id } },
    include: { lines: true, company: true, buyer: true },
  });
  if (!quote) return null;

  let brandName = quote.company.name || "Mannon";
  let primaryColor: string | null = null;
  try {
    const tokens = await getBrandingTokens(shopDomain);
    // Use the merchant's portal name only when they've customized their branding.
    if (tokens.custom && tokens.portalName) brandName = tokens.portalName;
    primaryColor = tokens.primary;
  } catch {
    /* no branding → company name + default colour */
  }

  const bytes = renderQuotePdfBytes({
    quoteRef: quote.id.slice(-8),
    createdAt: quote.createdAt,
    validUntil: quote.expiresAt,
    companyName: quote.company.name,
    buyerEmail: quote.buyer.email,
    poReference: quote.poReference,
    currencyCode: opts.currencyCode,
    lines: quote.lines.map((l) => ({ title: l.title, sku: l.sku, quantity: l.quantity, price: Number(l.price) })),
    brand: { name: brandName, primaryColor },
    whiteLabel: whiteLabelAllowed(opts.plan),
    locale: opts.locale,
  });

  return { filename: "quote.pdf", bytes, buyerEmail: quote.buyer.email, shopId: shop.id };
}
